version: '3'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/data/init.sql
    command: mysqld --init-file="init.sql"
    environment:
    - MYSQL_ROOT_PASSWORD= ""
    - MYSQL_USER= root
    - MYSQL_PASSWORD= ""
    - MYSQL_DATABASE= db_ms_identity_managment
