version: '3' 
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD= "admin"
    - MYSQL_USER= "admin"
    - MYSQL_PASSWORD= "admin"
    - MYSQL_DATABASE= "db_ms_identity_managment"
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS db_ms_identity_managment;
      "
