version: '3' 
services:
  db:
    image: mysql:5.7.25
    ports:
      - "3306:3306"
    command: --init-file config/init.sql
    volumes:
      - config/init.sql:/config/init.sql
    environment:
    - MYSQL_ROOT_PASSWORD= "admin"
    - MYSQL_USER= "admin"
    - MYSQL_PASSWORD= "admin"
    - MYSQL_DATABASE= "db_ms_identity_managment"
