version: '3' 
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD= "admin"
    - MYSQL_USER= "admin"
    - MYSQL_PASSWORD= "admin"
    - MYSQL_DATABASE= "db_ms_identity_managment"
